const Role = {
    PIMPINAN_PROVINSI: 1,
    KEPALA_BAGIAN_UMUM_PROVINSI: 2,
    KETUA_TIM_PROVINSI: 3,
    ANGGOTA_TIM_PROVINSI: 4,
    KEPALA_KABKO: 6,
    KEPALA_BAGIAN_UMUM_KABKO: 7,
    KETUA_TIM_KABKO: 8,
    ANGGOTA_TIM_KABKO: 9,
  };

  export default Role;